version: '3'

services:
  mysql:
    container_name: mysql_db
    image: mysql:8
    volumes:
      - mysql_volume:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_USER: ${DB_USER}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "--password=root" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: redis_db
    volumes:
      - redis_volume:/data

  minio:
    image: quay.io/minio/minio
    container_name: miniostorage
    volumes:
      - minio_volume:/data
    environment:
      MINIO_ROOT_USER: ${MINIO_LOGIN}
      MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD}
    command: [ "server", "/data", "--console-address", ":9001" ]

  cloud_storage:
    image: timmawv/cloud_storage
    container_name: cloud_storage
    environment:
      MINIO_HOST: ${MINIO_HOST}
      MINIO_PORT: ${MINIO_PORT}
      MINIO_LOGIN: ${MINIO_LOGIN}
      MINIO_PASSWORD: ${MINIO_PASSWORD}
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysql_volume:
  redis_volume:
  minio_volume: