version: '3'

services:
  mysql:
    container_name: mysql_db
    image: mysql:8
    volumes:
      - mysql_volume:/var/lib/mysql
    environment:
      MYSQL_DATABASE: file_storage
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 2s
      timeout: 10s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: redis_db
    volumes:
      - redis_volume:/data
    ports:
      - "6379:6379"


  minio:
    image: quay.io/minio/minio
    container_name: minio_storage
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_volume:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: ["server", "/data", "--console-address", ":9001"]

  cloud_storage:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      DB_USERNAME: root
      DB_PASSWORD: root
      DB_URL: jdbc:mysql://localhost:3306/file_storage
      MINIO_HOST: http://localhost:9000
      MINIO_LOGIN: minioadmin
      MINIO_PASSWORD: minioadmin
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysql_volume:
  redis_volume:
  minio_volume: