version: '3'

services:
  mysql:
    container_name: mysql_db
    image: mysql:8
    volumes:
      - mysql_volume:/var/lib/mysql
    environment:
      MYSQL_DATABASE: file_storage
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "--password=root" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: redis_db
    volumes:
      - redis_volume:/data
    ports:
      - "6379:6379"

  minio:
    image: quay.io/minio/minio
    container_name: miniostorage
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_volume:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: [ "server", "/data", "--console-address", ":9001" ]

  cloud_storage:
    image: timmawv/cloud_storage
    container_name: cloud_storage
    environment:
      MINIO_HOST: miniostorage
      MINIO_PORT: 9000
      MINIO_LOGIN: minioadmin
      MINIO_PASSWORD: minioadmin
      DB_USERNAME: root
      DB_PASSWORD: root
      DB_URL: jdbc:mysql://mysql_db:3306/file_storage
      REDIS_HOST: redis_db
      REDIS_PORT: 6379
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysql_volume:
  redis_volume:
  minio_volume: