spring:
  application:
    name: Cloud-File-Storage
  thymeleaf:
    cache: false
  devtools:
    restart:
      enabled: false
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
  session:
    timeout: 1800
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  liquibase:
    change-log: db/changelog/main-changelog.xml
  servlet:
    multipart:
      max-file-size: 120MB
      max-request-size: 120MB
      resolve-lazily: false
server:
  tomcat:
    max-swallow-size: -1
minio:
  host: ${MINIO_HOST}
  port: ${MINIO_PORT}
  login: ${MINIO_LOGIN}
  password: ${MINIO_PASSWORD}